### PR TITLE
Rails 4 0 3

### PR DESCRIPTION
**Pull request by hcarreras**
We should update to Rails 4.0.3 since it has important security fixes.
More info: http://weblog.rubyonrails.org/2014/2/18/Rails_3_2_17_4_0_3_and_4_1_0_beta2_have_been_released/?utm_source=rubyweekly&utm_medium=email

### CODE REVIEW

**Comment by voodoorai2000** [comment]
+1 Rails 4.0.3

**Comment by voodoorai2000** [comment]
There seems to be a problem merging this pull request.
What do you think it is?
https://travis-ci.org/PartidoDeInternet/AgoraOnRails/builds/19518817

**Comment by hcarreras** [comment]
I'm not sure how travis works (I just worked in project that use it, but I've never installed it).
Can you use a console? 
If is that possible try:
$ bundle update rails
And that should solve it.

**Comment by hcarreras** [comment]
Or could it be the Gemfile.lock?

**Comment by hcarreras** [comment]
Now, it is failing again. But it is for the devise config.secret_key
Right now is like:
config.secret_key = ENV['AGORAONRAILS_DEVISE_SECRET_KEY']
But it has an old key, we have to update it to '38494b6f83ac840c38b7f26dc0297eca09f673b7e04208c205f90400e19100ca9221fd373e64e080d18dfee7a6e411c8e9652890ce652e188a6b0f0d86d8f747'

I'm not very sure how can we changed it in the travis server...
Do you know how?

**Comment by voodoorai2000** [comment]
Travis is a beautiful service for Continuous Integration, which has become the standard in the rails open source world. I don't think we can access the console... but the logs usually show the key to the problem.

Indeed it looks like there is a problem with the Devise secret token...
I thought I fixed that a few weeks ago, encrypting the key for Travis[2]
Let me regenerate it... see if that fixes the build.

[2]http://docs.travis-ci.com/user/encryption-keys/

**Comment by voodoorai2000** [comment]
Regenerating the travis.yml fixed the build :)
https://travis-ci.org/PartidoDeInternet/AgoraOnRails

**Pull request merged**
